blank_issues_enabled: false
contact_links:
  - name: "❓ Question"
    url: https://github.com/thibaudcolas/draftjs-filters/discussions
    about: Use GitHub Discussions to get help with this project.
